# -*- coding: utf-8 -*-
"""Airline_Passenger_Satisfaction_Logistic_Regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PSPHHyclGhCmtifDqMUyoN-VVlDYn_6W
"""

import pandas as pd
import matplotlib.pyplot as plt


from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    classification_report,
    roc_auc_score,
    RocCurveDisplay
)
df = pd.read_csv("/Users/mubashirali/Documents/data.csv")

print("Shape:", df.shape)
print(df.head())

print("\nMissing Values:")
print(df.isnull().sum()[df.isnull().sum() > 0])

df["Arrival Delay in Minutes"] = df["Arrival Delay in Minutes"].fillna(
    df["Arrival Delay in Minutes"].median()
)

X = df.drop("satisfaction", axis=1)
y = df["satisfaction"].astype(int)

X = pd.get_dummies(X, drop_first=True)
